# Generated by Django 5.2.6 on 2025-10-04 09:50

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20250919_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmitCard',
        ),
        migrations.DeleteModel(
            name='CallLetter',
        ),
        migrations.DeleteModel(
            name='QuickLink',
        ),
        migrations.RemoveField(
            model_name='job',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='job',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='job',
            name='apply_online_link',
        ),
        migrations.RemoveField(
            model_name='job',
            name='education_qualification',
        ),
        migrations.RemoveField(
            model_name='job',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='exam_pattern',
        ),
        migrations.RemoveField(
            model_name='job',
            name='official_notification_link',
        ),
        migrations.RemoveField(
            model_name='job',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='post_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='job',
            name='total_vacancies',
        ),
        migrations.RemoveField(
            model_name='job',
            name='whatsapp_link',
        ),
        migrations.RemoveField(
            model_name='job',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='job',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='External Link'),
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[1200, 800], upload_to='jobs/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
