# Generated by Django 5.2.6 on 2025-10-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='apply_online_link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='education_qualification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='exam_pattern',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='official_notification_link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='total_vacancies',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='whatsapp_link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
